jobs:
  run:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./main/verify

name: Test

on:
  schedule:
    - cron: "15 1/3 * * *"
